name: event_emitter
version: 0.0.1
description: A Dart event emitter implementation withoud any dependencies.
authors:
  - axetroy <troy450409405@gmail.com>
homepage: https://github.com/axetroy/event-emitter.dart

dev_dependencies:
  test: